# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
