# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160611_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='alias',
            new_name='names',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='name',
        ),
    ]
