# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160610_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypeAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='persons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='alias',
            field=models.ManyToManyField(to='backend.TicketTypeAlias'),
        ),
    ]
